import type { Metadata } from 'next';
import './globals.scss';

import { useState, useEffect } from 'react';
import DataContext from '@/context/creation/createContext';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {

    const[data, setData] = useState<any>([]);

    useEffect(() => {

    }, []);

    return (
        <html lang='en'>
            <body>
                <DataContext.Provider value={{data, setData}}>
                    {children}
                </DataContext.Provider>
            </body>
        </html>
    )
}
